In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("Preprocessed_Data_Cryptos.csv")
dataset.head()

,symbol,Date,Time - 24 Hour Format,Time - 12 Hour Format,volume,open,Close Minus Open,Adj Close Minus Open,Close Minus Adj Close,High Minus Open,High Minus Close,High Minus Adj Close,High Minus Low,close,adj_close,high,low
0,BLY-USD,07-08-2020,00:00:00,12:00 AM,457741.0,0.039345,-0.011361,-0.011361,0.0,0.000035,0.011396,0.011396,0.011970,0.027984,0.027984,0.039380,0.027410
1,BLY-USD,08-08-2020,00:00:00,12:00 AM,339045.0,0.027906,-0.000211,-0.000211,0.0,0.000477,0.000688,0.000688,0.000741,0.027695,0.027695,0.028383,0.027642
2,BLY-USD,09-08-2020,00:00:00,12:00 AM,405214.0,0.027715,0.000071,0.000071,0.0,0.000250,0.000179,0.000179,0.001497,0.027786,0.027786,0.027965,0.026468
3,BLY-USD,10-08-2020,00:00:00,12:00 AM,452310.0,0.027835,-0.000978,-0.000978,0.0,0.001503,0.002481,0.002481,0.002486,0.026857,0.026857,0.029338,0.026852
4,BLY-USD,11-08-2020,00:00:00,12:00 AM,571556.0,0.026889,-0.000296,-0.000296,0.0,0.000368,0.000664,0.000664,0.001220,0.026593,0.026593,0.027257,0.026037

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048449 entries, 0 to 1048448
Data columns (total 17 columns):
symbol                   1048449 non-null object
Date                     1048449 non-null object
Time - 24 Hour Format    1048449 non-null object
Time - 12 Hour Format    1048449 non-null object
volume                   1048449 non-null float64
open                     1048449 non-null float64
Close Minus Open         1048449 non-null float64
Adj Close Minus Open     1048449 non-null float64
Close Minus Adj Close    1048449 non-null float64
High Minus Open          1048449 non-null float64
High Minus Close         1048449 non-null float64
High Minus Adj Close     1048449 non-null float64
High Minus Low           1048449 non-null float64
close                    1048449 non-null float64
adj_close                1048449 non-null float64
high                     1048449 non-null float64
low                      1048449 non-null float64
dtypes: float64(13), object(4)
memory usage: 136.0+ MB

In [4]:
dataset.columns

Index(['symbol', 'Date', 'Time - 24 Hour Format', 'Time - 12 Hour Format',
       'volume', 'open', 'Close Minus Open', 'Adj Close Minus Open',
       'Close Minus Adj Close', 'High Minus Open', 'High Minus Close',
       'High Minus Adj Close', 'High Minus Low', 'close', 'adj_close', 'high',
       'low'],
      dtype='object')

In [5]:
for columnName in dataset.columns:
    print(columnName)

symbol
Date
Time - 24 Hour Format
Time - 12 Hour Format
volume
open
Close Minus Open
Adj Close Minus Open
Close Minus Adj Close
High Minus Open
High Minus Close
High Minus Adj Close
High Minus Low
close
adj_close
high
low

In [6]:
if(dataset["open"].dtype=='O'):
    print("qual")
else:
    print("quan")

quan

In [7]:
quan=[]
qual=[]

for columnName in dataset.columns:
    #print(columnName)
    if(dataset[columnName].dtype=='O'): #if the Datatype of Variable - columnName is Object
        #print("qual")
        qual.append(columnName) #It will append (Add) that columnName into an Existing List - qual 
    else:
        #print("quan")
        quan.append(columnName) #Else, It will append (Add) that columnName into an Existing List - quan

In [8]:
quan

['volume',
 'open',
 'Close Minus Open',
 'Adj Close Minus Open',
 'Close Minus Adj Close',
 'High Minus Open',
 'High Minus Close',
 'High Minus Adj Close',
 'High Minus Low',
 'close',
 'adj_close',
 'high',
 'low']

In [9]:
qual

['symbol', 'Date', 'Time - 24 Hour Format', 'Time - 12 Hour Format']

In [10]:
def quanQual(dataset):
    
    quan=[]
    qual=[]
    
    for columnName in dataset.columns:
        #print(columnName)
        if(dataset[columnName].dtype=='O'):
            #print("qual")
            qual.append(columnName)
        else:
            #print("quan")
            quan.append(columnName)
    return quan,qual

In [11]:
quanQual(dataset)

(['volume',
  'open',
  'Close Minus Open',
  'Adj Close Minus Open',
  'Close Minus Adj Close',
  'High Minus Open',
  'High Minus Close',
  'High Minus Adj Close',
  'High Minus Low',
  'close',
  'adj_close',
  'high',
  'low'],
 ['symbol', 'Date', 'Time - 24 Hour Format', 'Time - 12 Hour Format'])

In [12]:
quan,qual = quanQual(dataset)
quan, qual

(['volume',
  'open',
  'Close Minus Open',
  'Adj Close Minus Open',
  'Close Minus Adj Close',
  'High Minus Open',
  'High Minus Close',
  'High Minus Adj Close',
  'High Minus Low',
  'close',
  'adj_close',
  'high',
  'low'],
 ['symbol', 'Date', 'Time - 24 Hour Format', 'Time - 12 Hour Format'])

#Central Tendency

In [13]:
dataset.describe() #Here, Median, Mode are Missing. So we need to create our own Function

,volume,open,Close Minus Open,Adj Close Minus Open,Close Minus Adj Close,High Minus Open,High Minus Close,High Minus Adj Close,High Minus Low,close,adj_close,high,low
count,1.048449e+06,1.048449e+06,1.048449e+06,1.048449e+06,1.048449e+06,1.048449e+06,1.048449e+06,1.048449e+06,1.048449e+06,1.048449e+06,1.048449e+06,1.048449e+06,1.048449e+06
mean,2.110939e+08,3.753280e+02,3.277359e-01,2.965013e-01,3.123459e-02,2.522343e+01,2.489570e+01,2.492693e+01,3.465481e+01,3.756595e+02,3.756279e+02,4.008336e+02,3.657912e+02
std,3.335085e+09,4.554186e+03,3.217933e+02,3.217936e+02,4.384441e-01,1.422481e+04,1.422661e+04,1.422661e+04,1.423401e+04,4.558237e+03,4.558239e+03,1.497789e+04,4.433198e+03
min,0.000000e+00,0.000000e+00,-2.011313e+05,-2.011313e+05,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,1.475610e+05,1.422500e-02,-3.721997e-03,-4.045993e-03,0.000000e+00,1.730000e-04,2.609990e-04,2.610000e-04,8.410000e-04,1.419800e-02,1.419800e-02,1.510600e-02,1.343200e-02
50%,1.050700e+06,1.451690e-01,-1.000000e-06,-2.000000e-06,0.000000e+00,2.618000e-03,3.332973e-03,3.337979e-03,8.902997e-03,1.449930e-01,1.449930e-01,1.529530e-01,1.376110e-01
75%,8.867994e+06,1.227162e+00,2.339005e-03,2.131000e-03,0.000000e+00,3.093004e-02,3.657496e-02,3.706098e-02,8.577395e-02,1.225580e+00,1.225580e+00,1.291171e+00,1.168916e+00
max,6.070000e+11,2.998433e+05,1.558728e+05,1.558728e+05,1.295310e+01,1.453538e+07,1.453537e+07,1.453537e+07,1.453540e+07,2.998433e+05,2.998433e+05,1.453542e+07,1.515297e+05

In [14]:
descriptive = pd.DataFrame() #The Keyword - DataFrame Will create a Table
descriptive #The Output is Just a _ Because we did not declare any Index and Column Name(s)

Empty DataFrame
Columns: []
Index: []

In [15]:
descriptive = pd.DataFrame(index=["Mean","Median","Mode"],columns=quan)
descriptive

,volume,open,Close Minus Open,Adj Close Minus Open,Close Minus Adj Close,High Minus Open,High Minus Close,High Minus Adj Close,High Minus Low,close,adj_close,high,low
Mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Median,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Mode,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
#To Automate the "Mean","Median","Mode" to be filled in Table automatically

descriptive = pd.DataFrame(index=["Mean","Median","Mode"],columns=quan)

for columnName in quan:
    descriptive[columnName]["Mean"] = dataset[columnName].mean()
    descriptive[columnName]["Median"] = dataset[columnName].median()
    descriptive[columnName]["Mode"] = dataset[columnName].mode()[0]

descriptive

,volume,open,Close Minus Open,Adj Close Minus Open,Close Minus Adj Close,High Minus Open,High Minus Close,High Minus Adj Close,High Minus Low,close,adj_close,high,low
Mean,2.11094e+08,375.328,0.327736,0.296501,0.0312346,25.2234,24.8957,24.9269,34.6548,375.659,375.628,400.834,365.791
Median,1.0507e+06,0.145169,-1e-06,-2e-06,0,0.002618,0.00333297,0.00333798,0.008903,0.144993,0.144993,0.152953,0.137611
Mode,0,0,0,0,0,0,0,0,0,0,0,0,0

### Percentile

In [17]:
import numpy as np

In [18]:
#To Verify any Levels (25%, 50% etc) of Percentile
np.percentile(dataset["open"],25)

0.014225

In [19]:
#To Automate the "Mean","Median","Mode" and "Level of Percentile" to be filled in Table automatically

descriptive = pd.DataFrame(index=["Mean","Median","Mode","Q1:25%","Q2:50%","Q3:75%","99%","Q4:100%"],columns=quan)

for columnName in quan:
    descriptive[columnName]["Mean"] = dataset[columnName].mean()
    descriptive[columnName]["Median"] = dataset[columnName].median()
    descriptive[columnName]["Mode"] = dataset[columnName].mode()[0]
    descriptive[columnName]["Q1:25%"] = dataset.describe()[columnName]["25%"]
    descriptive[columnName]["Q2:50%"] = dataset.describe()[columnName]["50%"]
    descriptive[columnName]["Q3:75%"] = dataset.describe()[columnName]["75%"]
    descriptive[columnName]["99%"] = np.percentile(dataset[columnName],99)
    descriptive[columnName]["Q4:100%"] = dataset.describe()[columnName]["max"]

descriptive

,volume,open,Close Minus Open,Adj Close Minus Open,Close Minus Adj Close,High Minus Open,High Minus Close,High Minus Adj Close,High Minus Low,close,adj_close,high,low
Mean,2.11094e+08,375.328,0.327736,0.296501,0.0312346,25.2234,24.8957,24.9269,34.6548,375.659,375.628,400.834,365.791
Median,1.0507e+06,0.145169,-1e-06,-2e-06,0,0.002618,0.00333297,0.00333798,0.008903,0.144993,0.144993,0.152953,0.137611
Mode,0,0,0,0,0,0,0,0,0,0,0,0,0
Q1:25%,147561,0.014225,-0.003722,-0.00404599,0,0.000173,0.000260999,0.000261,0.000841,0.014198,0.014198,0.015106,0.013432
Q2:50%,1.0507e+06,0.145169,-1e-06,-2e-06,0,0.002618,0.00333297,0.00333798,0.008903,0.144993,0.144993,0.152953,0.137611
Q3:75%,8.86799e+06,1.22716,0.002339,0.002131,0,0.03093,0.036575,0.037061,0.0857739,1.22558,1.22558,1.29117,1.16892
99%,2.13017e+09,3539.28,29.3411,29.3411,0.38747,89.1644,92.4965,92.4965,197.601,3538.86,3538.86,3627.64,3459.77
Q4:100%,6.07e+11,299843,155873,155873,12.9531,1.45354e+07,1.45354e+07,1.45354e+07,1.45354e+07,299843,299843,1.45354e+07,151530

In [20]:
"""
Dataset (With Outliers)
To Automate the "Mean","Median","Mode" and "Level of Percentile"("Q1:25%","Q2:50%","Q3:75%","99%","Q4:100%"),
"IQR","1.5_rule","LesserOutlier","GreaterOutlier","MinValue","MaxValue" to be filled in Table automatically
"""

descriptive = pd.DataFrame(index=["Mean","Median","Mode","Q1:25%","Q2:50%","Q3:75%","99%","Q4:100%","IQR","1.5_rule",
                                  "LesserOutlier","GreaterOutlier","MinValue","MaxValue"],columns=quan)

for columnName in quan:
    descriptive[columnName]["Mean"] = dataset[columnName].mean()
    descriptive[columnName]["Median"] = dataset[columnName].median()
    descriptive[columnName]["Mode"] = dataset[columnName].mode()[0]
    descriptive[columnName]["Q1:25%"] = dataset.describe()[columnName]["25%"]
    descriptive[columnName]["Q2:50%"] = dataset.describe()[columnName]["50%"]
    descriptive[columnName]["Q3:75%"] = dataset.describe()[columnName]["75%"]
    descriptive[columnName]["99%"] = np.percentile(dataset[columnName],99)
    descriptive[columnName]["Q4:100%"] = dataset.describe()[columnName]["max"]
    
    descriptive[columnName]["IQR"] = descriptive[columnName]["Q3:75%"] - descriptive[columnName]["Q1:25%"]
    descriptive[columnName]["1.5_rule"] = 1.5 * descriptive[columnName]["IQR"]
    descriptive[columnName]["LesserOutlier"] = descriptive[columnName]["Q1:25%"] - descriptive[columnName]["1.5_rule"]
    descriptive[columnName]["GreaterOutlier"] = descriptive[columnName]["Q3:75%"] + descriptive[columnName]["1.5_rule"]
    descriptive[columnName]["MinValue"] = dataset[columnName].min()
    descriptive[columnName]["MaxValue"] = dataset[columnName].max()

descriptive

,volume,open,Close Minus Open,Adj Close Minus Open,Close Minus Adj Close,High Minus Open,High Minus Close,High Minus Adj Close,High Minus Low,close,adj_close,high,low
Mean,2.11094e+08,375.328,0.327736,0.296501,0.0312346,25.2234,24.8957,24.9269,34.6548,375.659,375.628,400.834,365.791
Median,1.0507e+06,0.145169,-1e-06,-2e-06,0,0.002618,0.00333297,0.00333798,0.008903,0.144993,0.144993,0.152953,0.137611
Mode,0,0,0,0,0,0,0,0,0,0,0,0,0
Q1:25%,147561,0.014225,-0.003722,-0.00404599,0,0.000173,0.000260999,0.000261,0.000841,0.014198,0.014198,0.015106,0.013432
Q2:50%,1.0507e+06,0.145169,-1e-06,-2e-06,0,0.002618,0.00333297,0.00333798,0.008903,0.144993,0.144993,0.152953,0.137611
Q3:75%,8.86799e+06,1.22716,0.002339,0.002131,0,0.03093,0.036575,0.037061,0.0857739,1.22558,1.22558,1.29117,1.16892
99%,2.13017e+09,3539.28,29.3411,29.3411,0.38747,89.1644,92.4965,92.4965,197.601,3538.86,3538.86,3627.64,3459.77
Q4:100%,6.07e+11,299843,155873,155873,12.9531,1.45354e+07,1.45354e+07,1.45354e+07,1.45354e+07,299843,299843,1.45354e+07,151530
IQR,8.72043e+06,1.21294,0.006061,0.00617699,0,0.030757,0.036314,0.0368,0.0849329,1.21138,1.21138,1.27606,1.15548
1.5_rule,1.30806e+07,1.81941,0.0090915,0.00926549,0,0.0461356,0.0544709,0.0552,0.127399,1.81707,1.81707,1.9141,1.73323
LesserOutlier,-1.29331e+07,-1.80518,-0.0128135,-0.0133115,0,-0.0459626,-0.0542099,-0.054939,-0.126558,-1.80287,-1.80287,-1.89899,-1.71979
GreaterOutlier,2.19486e+07,3.04657,0.0114305,0.0113965,0,0.0770656,0.0910459,0.0922609,0.213173,3.04265,3.04265,3.20527,2.90214
MinValue,0,0,-201131,-201131,0,0,0,0,0,0,0,0,0
MaxValue,6.07e+11,299843,155873,155873,12.9531,1.45354e+07,1.45354e+07,1.45354e+07,1.45354e+07,299843,299843,1.45354e+07,151530

In [21]:
#To Findout Presence of Outliers in Column(s) 

LesserOutlierColumnName=[]
GreaterOutlierColumnName=[]

for checkOutlierColumnName in quan :
    if (descriptive[checkOutlierColumnName]["MinValue"] < descriptive[checkOutlierColumnName]["LesserOutlier"]):
        LesserOutlierColumnName.append(checkOutlierColumnName)        
    if (descriptive[checkOutlierColumnName]["MaxValue"] > descriptive[checkOutlierColumnName]["GreaterOutlier"]):
        GreaterOutlierColumnName.append(checkOutlierColumnName)
        
print(f"{LesserOutlierColumnName}\n{GreaterOutlierColumnName}")

['Close Minus Open', 'Adj Close Minus Open']
['volume', 'open', 'Close Minus Open', 'Adj Close Minus Open', 'Close Minus Adj Close', 'High Minus Open', 'High Minus Close', 'High Minus Adj Close', 'High Minus Low', 'close', 'adj_close', 'high', 'low']

In [22]:
#Creating a Function - OutlierColumnNames(with Parameter) To Automate by Findingout the Presence of Outliers in Column(s) 

def OutlierColumnNames(quan):

    LesserOutlierColumnName=[]
    GreaterOutlierColumnName=[]

    for checkOutlierColumnName in quan :
        if (descriptive[checkOutlierColumnName]["MinValue"] < descriptive[checkOutlierColumnName]["LesserOutlier"]):
            LesserOutlierColumnName.append(checkOutlierColumnName)        
        if (descriptive[checkOutlierColumnName]["MaxValue"] > descriptive[checkOutlierColumnName]["GreaterOutlier"]):
            GreaterOutlierColumnName.append(checkOutlierColumnName)

    return (f"{LesserOutlierColumnName}\n{GreaterOutlierColumnName}")

In [23]:
OutlierColumnNames(quan)

"['Close Minus Open', 'Adj Close Minus Open']\n['volume', 'open', 'Close Minus Open', 'Adj Close Minus Open', 'Close Minus Adj Close', 'High Minus Open', 'High Minus Close', 'High Minus Adj Close', 'High Minus Low', 'close', 'adj_close', 'high', 'low']"

In [24]:
#To Replace the Existing Outlier in Dataset

LesserOutlierColumnName=[]
GreaterOutlierColumnName=[]

for columnName in LesserOutlierColumnName:
    dataset[columnName][dataset[columnName] < descriptive[checkOutlierColumnName]["LesserOutlier"]] = descriptive[checkOutlierColumnName]["LesserOutlier"]
for columnName in GreaterOutlierColumnName:
    dataset[columnName][dataset[columnName] > descriptive[checkOutlierColumnName]["GreaterOutlier"]] = descriptive[checkOutlierColumnName]["GreaterOutlier"]

In [25]:
"""Creating a Function - ReplaceOutliers (with Parameter) To Automate by Replacing the Existing Outlier in Dataset"""

def ReplaceOutliers(LesserOutlierColumnName,dataset,checkOutlierColumnName,GreaterOutlierColumnName):
    for columnName in LesserOutlierColumnName:
        dataset[columnName][dataset[columnName] < descriptive[checkOutlierColumnName]["LesserOutlier"]] = descriptive[checkOutlierColumnName]["LesserOutlier"]
    for columnName in GreaterOutlierColumnName:
        dataset[columnName][dataset[columnName] > descriptive[checkOutlierColumnName]["GreaterOutlier"]] = descriptive[checkOutlierColumnName]["GreaterOutlier"]

In [26]:
ReplaceOutliers(LesserOutlierColumnName,dataset,checkOutlierColumnName,GreaterOutlierColumnName)

In [27]:
""" To Cross check the Updated Dataset (Without Outliers) is Updated or Not by Univariating
To Automate the "Mean","Median","Mode" and "Level of Percentile"("Q1:25%","Q2:50%","Q3:75%","99%","Q4:100%"),
"IQR","1.5_rule","LesserOutlier","GreaterOutlier","MinValue","MaxValue" to be filled in Table automatically
"""

descriptive = pd.DataFrame(index=["Mean","Median","Mode","Q1:25%","Q2:50%","Q3:75%","99%","Q4:100%","IQR","1.5_rule",
                                  "LesserOutlier","GreaterOutlier","MinValue","MaxValue"],columns=quan)

for columnName in quan:
    descriptive[columnName]["Mean"] = dataset[columnName].mean()
    descriptive[columnName]["Median"] = dataset[columnName].median()
    descriptive[columnName]["Mode"] = dataset[columnName].mode()[0]
    descriptive[columnName]["Q1:25%"] = dataset.describe()[columnName]["25%"]
    descriptive[columnName]["Q2:50%"] = dataset.describe()[columnName]["50%"]
    descriptive[columnName]["Q3:75%"] = dataset.describe()[columnName]["75%"]
    descriptive[columnName]["99%"] = np.percentile(dataset[columnName],99)
    descriptive[columnName]["Q4:100%"] = dataset.describe()[columnName]["max"]
    
    descriptive[columnName]["IQR"] = descriptive[columnName]["Q3:75%"] - descriptive[columnName]["Q1:25%"]
    descriptive[columnName]["1.5_rule"] = 1.5 * descriptive[columnName]["IQR"]
    descriptive[columnName]["LesserOutlier"] = descriptive[columnName]["Q1:25%"] - descriptive[columnName]["1.5_rule"]
    descriptive[columnName]["GreaterOutlier"] = descriptive[columnName]["Q3:75%"] + descriptive[columnName]["1.5_rule"]
    descriptive[columnName]["MinValue"] = dataset[columnName].min()
    descriptive[columnName]["MaxValue"] = dataset[columnName].max()

descriptive

,volume,open,Close Minus Open,Adj Close Minus Open,Close Minus Adj Close,High Minus Open,High Minus Close,High Minus Adj Close,High Minus Low,close,adj_close,high,low
Mean,2.11094e+08,375.328,0.327736,0.296501,0.0312346,25.2234,24.8957,24.9269,34.6548,375.659,375.628,400.834,365.791
Median,1.0507e+06,0.145169,-1e-06,-2e-06,0,0.002618,0.00333297,0.00333798,0.008903,0.144993,0.144993,0.152953,0.137611
Mode,0,0,0,0,0,0,0,0,0,0,0,0,0
Q1:25%,147561,0.014225,-0.003722,-0.00404599,0,0.000173,0.000260999,0.000261,0.000841,0.014198,0.014198,0.015106,0.013432
Q2:50%,1.0507e+06,0.145169,-1e-06,-2e-06,0,0.002618,0.00333297,0.00333798,0.008903,0.144993,0.144993,0.152953,0.137611
Q3:75%,8.86799e+06,1.22716,0.002339,0.002131,0,0.03093,0.036575,0.037061,0.0857739,1.22558,1.22558,1.29117,1.16892
99%,2.13017e+09,3539.28,29.3411,29.3411,0.38747,89.1644,92.4965,92.4965,197.601,3538.86,3538.86,3627.64,3459.77
Q4:100%,6.07e+11,299843,155873,155873,12.9531,1.45354e+07,1.45354e+07,1.45354e+07,1.45354e+07,299843,299843,1.45354e+07,151530
IQR,8.72043e+06,1.21294,0.006061,0.00617699,0,0.030757,0.036314,0.0368,0.0849329,1.21138,1.21138,1.27606,1.15548
1.5_rule,1.30806e+07,1.81941,0.0090915,0.00926549,0,0.0461356,0.0544709,0.0552,0.127399,1.81707,1.81707,1.9141,1.73323
LesserOutlier,-1.29331e+07,-1.80518,-0.0128135,-0.0133115,0,-0.0459626,-0.0542099,-0.054939,-0.126558,-1.80287,-1.80287,-1.89899,-1.71979
GreaterOutlier,2.19486e+07,3.04657,0.0114305,0.0113965,0,0.0770656,0.0910459,0.0922609,0.213173,3.04265,3.04265,3.20527,2.90214
MinValue,0,0,-201131,-201131,0,0,0,0,0,0,0,0,0
MaxValue,6.07e+11,299843,155873,155873,12.9531,1.45354e+07,1.45354e+07,1.45354e+07,1.45354e+07,299843,299843,1.45354e+07,151530

In [28]:
"""
To Cross check the Updated Dataset (Without Outliers) is Updated or Not
To Findout Presence of Outliers in Column(s) 
"""

LesserOutlierColumnName=[]
GreaterOutlierColumnName=[]

for checkOutlierColumnName in quan :
    if (descriptive[checkOutlierColumnName]["MinValue"] < descriptive[checkOutlierColumnName]["LesserOutlier"]):
        LesserOutlierColumnName.append(checkOutlierColumnName)        
    if (descriptive[checkOutlierColumnName]["MaxValue"] > descriptive[checkOutlierColumnName]["GreaterOutlier"]):
        GreaterOutlierColumnName.append(checkOutlierColumnName)
        
print(f"{LesserOutlierColumnName}\n{GreaterOutlierColumnName}")

['Close Minus Open', 'Adj Close Minus Open']
['volume', 'open', 'Close Minus Open', 'Adj Close Minus Open', 'Close Minus Adj Close', 'High Minus Open', 'High Minus Close', 'High Minus Adj Close', 'High Minus Low', 'close', 'adj_close', 'high', 'low']

In [29]:
"""Creating a Function To Automate the "Mean","Median","Mode" and "Level of Percentile"("Q1:25%","Q2:50%","Q3:75%","99%","Q4:100%"),
"IQR","1.5_rule","LesserOutlier","GreaterOutlier","MinValue","MaxValue", "Skewness", "Kurtosis", "Variance", "StdDeviation" 
to be filled in Table automatically """

def Univariate(dataset,quan):
    descriptive = pd.DataFrame(index=["Mean","Median","Mode","Q1:25%","Q2:50%","Q3:75%","99%","Q4:100%","IQR","1.5_rule",
                        "LesserOutlier","GreaterOutlier","MinValue","MaxValue","Skewness","Kurtosis",
                                      "Variance","StdDeviation"],columns=quan)

    for columnName in quan:
            descriptive[columnName]["Mean"] = dataset[columnName].mean()
            descriptive[columnName]["Median"] = dataset[columnName].median()
            descriptive[columnName]["Mode"] = dataset[columnName].mode()[0]
            descriptive[columnName]["Q1:25%"] = dataset.describe()[columnName]["25%"]
            descriptive[columnName]["Q2:50%"] = dataset.describe()[columnName]["50%"]
            descriptive[columnName]["Q3:75%"] = dataset.describe()[columnName]["75%"]
            descriptive[columnName]["99%"] = np.percentile(dataset[columnName],99)
            descriptive[columnName]["Q4:100%"] = dataset.describe()[columnName]["max"]

            descriptive[columnName]["IQR"] = descriptive[columnName]["Q3:75%"] - descriptive[columnName]["Q1:25%"]
            descriptive[columnName]["1.5_rule"] = 1.5 * descriptive[columnName]["IQR"]
            descriptive[columnName]["LesserOutlier"] = descriptive[columnName]["Q1:25%"] - descriptive[columnName]["1.5_rule"]
            descriptive[columnName]["GreaterOutlier"] = descriptive[columnName]["Q3:75%"] + descriptive[columnName]["1.5_rule"]
            descriptive[columnName]["MinValue"] = dataset[columnName].min()
            descriptive[columnName]["MaxValue"] = dataset[columnName].max()
            
            descriptive[columnName]["Skewness"] = dataset[columnName].skew()
            descriptive[columnName]["Kurtosis"] = dataset[columnName].kurtosis()
            
            descriptive[columnName]["Variance"] = dataset[columnName].var()
            descriptive[columnName]["StdDeviation"] = dataset[columnName].std()
        
    return descriptive

In [35]:
#1. Import the class from the file
from UnivariateFile import UnivariateClass

In [36]:
#2. Create an object of the class
obj = UnivariateClass()

In [38]:
#3. Call the method (function inside class)
Univariate(dataset, quan)

,volume,open,Close Minus Open,Adj Close Minus Open,Close Minus Adj Close,High Minus Open,High Minus Close,High Minus Adj Close,High Minus Low,close,adj_close,high,low
Mean,2.11094e+08,375.328,0.327736,0.296501,0.0312346,25.2234,24.8957,24.9269,34.6548,375.659,375.628,400.834,365.791
Median,1.0507e+06,0.145169,-1e-06,-2e-06,0,0.002618,0.00333297,0.00333798,0.008903,0.144993,0.144993,0.152953,0.137611
Mode,0,0,0,0,0,0,0,0,0,0,0,0,0
Q1:25%,147561,0.014225,-0.003722,-0.00404599,0,0.000173,0.000260999,0.000261,0.000841,0.014198,0.014198,0.015106,0.013432
Q2:50%,1.0507e+06,0.145169,-1e-06,-2e-06,0,0.002618,0.00333297,0.00333798,0.008903,0.144993,0.144993,0.152953,0.137611
Q3:75%,8.86799e+06,1.22716,0.002339,0.002131,0,0.03093,0.036575,0.037061,0.0857739,1.22558,1.22558,1.29117,1.16892
99%,2.13017e+09,3539.28,29.3411,29.3411,0.38747,89.1644,92.4965,92.4965,197.601,3538.86,3538.86,3627.64,3459.77
Q4:100%,6.07e+11,299843,155873,155873,12.9531,1.45354e+07,1.45354e+07,1.45354e+07,1.45354e+07,299843,299843,1.45354e+07,151530
IQR,8.72043e+06,1.21294,0.006061,0.00617699,0,0.030757,0.036314,0.0368,0.0849329,1.21138,1.21138,1.27606,1.15548
1.5_rule,1.30806e+07,1.81941,0.0090915,0.00926549,0,0.0461356,0.0544709,0.0552,0.127399,1.81707,1.81707,1.9141,1.73323
LesserOutlier,-1.29331e+07,-1.80518,-0.0128135,-0.0133115,0,-0.0459626,-0.0542099,-0.054939,-0.126558,-1.80287,-1.80287,-1.89899,-1.71979
GreaterOutlier,2.19486e+07,3.04657,0.0114305,0.0113965,0,0.0770656,0.0910459,0.0922609,0.213173,3.04265,3.04265,3.20527,2.90214
MinValue,0,0,-201131,-201131,0,0,0,0,0,0,0,0,0
MaxValue,6.07e+11,299843,155873,155873,12.9531,1.45354e+07,1.45354e+07,1.45354e+07,1.45354e+07,299843,299843,1.45354e+07,151530
Skewness,38.5138,17.2104,-114.563,-114.562,19.7115,1017.75,1017.38,1017.38,1015.81,17.2014,17.2014,872.344,16.9139
Kurtosis,2606.77,336.858,204658,204657,443.158,1.03986e+06,1.03933e+06,1.03933e+06,1.03717e+06,336.364,336.364,845899,312.428
Variance,1.11228e+19,2.07406e+07,103551,103551,0.192233,2.02345e+08,2.02396e+08,2.02396e+08,2.02607e+08,2.07775e+07,2.07775e+07,2.24337e+08,1.96532e+07
StdDeviation,3.33508e+09,4554.19,321.793,321.794,0.438444,14224.8,14226.6,14226.6,14234,4558.24,4558.24,14977.9,4433.2

### Frequency

In [ ]:
"""
Purpose: It gives Both Unique Values and Repeatation of Each Unique Values
"""
dataset["open"].value_counts()

In [39]:
"""
Purpose: It gives Only Unique Values
"""
dataset["open"].value_counts().index

Float64Index([               0.0,  375.3280493887282,              1e-06,
                           2e-06,              3e-06,              4e-06,
                           5e-06,              6e-06,            1.2e-05,
                           9e-06,
              ...
                     0.242572993,        0.100382999,        2365.213623,
              2.8803210260000003,        0.185541004, 1.7076699730000002,
                     1.314370036,        0.080751002,        0.611800015,
                     3.463459969],
             dtype='float64', length=575371)

In [40]:
"""
Purpose: It gives Only the Repeatation (Count) of Each Unique Values
"""
dataset["open"].value_counts().values

array([18595, 11597,  4253, ...,     1,     1,     1], dtype=int64)

In [42]:
"""
Purpose: It gives Only Sorted Unique Values
"""
dataset["open"].value_counts().sort_index

<bound method Series.sort_index of 0.000000      18595
375.328049    11597
0.000001       4253
0.000002       2239
0.000003       1827
              ...
1.707670          1
1.314370          1
0.080751          1
0.611800          1
3.463460          1
Name: open, Length: 575371, dtype: int64>

In [43]:
"""
Purpose: It gives Only Sorted Repeatation (Sorted Count) of Each Unique Values
"""
dataset["open"].value_counts().sort_values

<bound method Series.sort_values of 0.000000      18595
375.328049    11597
0.000001       4253
0.000002       2239
0.000003       1827
              ...
1.707670          1
1.314370          1
0.080751          1
0.611800          1
3.463460          1
Name: open, Length: 575371, dtype: int64>

In [44]:
"""
Checking the Base Working Logic for Frequency, Relative Frequency and Cumulative Relative Frequency 
by Creating a New Table - FrequencyTable
"""
frequencyTable = pd.DataFrame(columns=["Unique_Values","Frequency","Relative_Frequency","CumSum"])
frequencyTable

Empty DataFrame
Columns: [Unique_Values, Frequency, Relative_Frequency, CumSum]
Index: []

In [45]:
total = len(dataset)
total

1048449

In [46]:
"""
Checking the Base Working Logic for Frequency, Relative Frequency and Cumulative Relative Frequency 
by Creating a New Table - FrequencyTable
"""
frequencyTable["Unique_Values"] = dataset["open"].value_counts().index
frequencyTable["Frequency"] = dataset["open"].value_counts().values
frequencyTable["Relative_Frequency"] = (frequencyTable["Frequency"]/103)
frequencyTable["CumSum"] = frequencyTable["Relative_Frequency"].cumsum() #Calling an Existing Function .cumsum()

frequencyTable

        Unique_Values  Frequency  Relative_Frequency        CumSum
0            0.000000      18595          180.533981    180.533981
1          375.328049      11597          112.592233    293.126214
2            0.000001       4253           41.291262    334.417476
3            0.000002       2239           21.737864    356.155340
4            0.000003       1827           17.737864    373.893204
...               ...        ...                 ...           ...
575366       1.707670          1            0.009709  10179.077670
575367       1.314370          1            0.009709  10179.087379
575368       0.080751          1            0.009709  10179.097087
575369       0.611800          1            0.009709  10179.106796
575370       3.463460          1            0.009709  10179.116505

[575371 rows x 4 columns]

In [47]:
"""Creating a Function To Automate the Updatation of Frequency, Relative Frequency and Cumulative Relative Frequency 
by Creating a New Table - FrequencyTable """

def frequencyTable(dataset,columnName):
    frequencyTable = pd.DataFrame(columns=["Unique_Values","Frequency","Relative_Frequency","CumSum"])
    frequencyTable["Unique_Values"] = dataset[columnName].value_counts().index
    frequencyTable["Frequency"] = dataset[columnName].value_counts().values
    frequencyTable["Relative_Frequency"] = (frequencyTable["Frequency"]/103)
    frequencyTable["CumSum"] = frequencyTable["Relative_Frequency"].cumsum() #Calling an Existing Function .cumsum()
    return frequencyTable

In [48]:
frequencyTable(dataset,columnName)

        Unique_Values  Frequency  Relative_Frequency        CumSum
0            0.000000      18825          182.766990    182.766990
1          365.791182      11597          112.592233    295.359223
2            0.000001       4285           41.601942    336.961165
3            0.000002       2263           21.970874    358.932039
4            0.000003       1818           17.650485    376.582524
...               ...        ...                 ...           ...
570480       0.656995          1            0.009709  10179.077670
570481       0.128494          1            0.009709  10179.087379
570482       1.657303          1            0.009709  10179.097087
570483       0.670363          1            0.009709  10179.106796
570484     203.602448          1            0.009709  10179.116505

[570485 rows x 4 columns]

### Skewness

In [49]:
""" 
Purpose: It gives Peak of the Graph which May Equal to 3, Lesser than 3 Or Greater than 3. Each Level Indicates below categories
1.Platykurtic <3 , 2.Mesokurtic =3 , 3.Leptokurtic >3 
Adding this Skew and Kurtosis to Function - Univariate which present in the Class - Univariate
"""
dataset.skew()

volume                     38.513773
open                       17.210443
Close Minus Open         -114.562701
Adj Close Minus Open     -114.562057
Close Minus Adj Close      19.711534
High Minus Open          1017.751025
High Minus Close         1017.379916
High Minus Adj Close     1017.379919
High Minus Low           1015.810781
close                      17.201364
adj_close                  17.201363
high                      872.343793
low                        16.913914
dtype: float64

In [51]:
Univariate(dataset,quan)

,volume,open,Close Minus Open,Adj Close Minus Open,Close Minus Adj Close,High Minus Open,High Minus Close,High Minus Adj Close,High Minus Low,close,adj_close,high,low
Mean,2.11094e+08,375.328,0.327736,0.296501,0.0312346,25.2234,24.8957,24.9269,34.6548,375.659,375.628,400.834,365.791
Median,1.0507e+06,0.145169,-1e-06,-2e-06,0,0.002618,0.00333297,0.00333798,0.008903,0.144993,0.144993,0.152953,0.137611
Mode,0,0,0,0,0,0,0,0,0,0,0,0,0
Q1:25%,147561,0.014225,-0.003722,-0.00404599,0,0.000173,0.000260999,0.000261,0.000841,0.014198,0.014198,0.015106,0.013432
Q2:50%,1.0507e+06,0.145169,-1e-06,-2e-06,0,0.002618,0.00333297,0.00333798,0.008903,0.144993,0.144993,0.152953,0.137611
Q3:75%,8.86799e+06,1.22716,0.002339,0.002131,0,0.03093,0.036575,0.037061,0.0857739,1.22558,1.22558,1.29117,1.16892
99%,2.13017e+09,3539.28,29.3411,29.3411,0.38747,89.1644,92.4965,92.4965,197.601,3538.86,3538.86,3627.64,3459.77
Q4:100%,6.07e+11,299843,155873,155873,12.9531,1.45354e+07,1.45354e+07,1.45354e+07,1.45354e+07,299843,299843,1.45354e+07,151530
IQR,8.72043e+06,1.21294,0.006061,0.00617699,0,0.030757,0.036314,0.0368,0.0849329,1.21138,1.21138,1.27606,1.15548
1.5_rule,1.30806e+07,1.81941,0.0090915,0.00926549,0,0.0461356,0.0544709,0.0552,0.127399,1.81707,1.81707,1.9141,1.73323
LesserOutlier,-1.29331e+07,-1.80518,-0.0128135,-0.0133115,0,-0.0459626,-0.0542099,-0.054939,-0.126558,-1.80287,-1.80287,-1.89899,-1.71979
GreaterOutlier,2.19486e+07,3.04657,0.0114305,0.0113965,0,0.0770656,0.0910459,0.0922609,0.213173,3.04265,3.04265,3.20527,2.90214
MinValue,0,0,-201131,-201131,0,0,0,0,0,0,0,0,0
MaxValue,6.07e+11,299843,155873,155873,12.9531,1.45354e+07,1.45354e+07,1.45354e+07,1.45354e+07,299843,299843,1.45354e+07,151530
Skewness,38.5138,17.2104,-114.563,-114.562,19.7115,1017.75,1017.38,1017.38,1015.81,17.2014,17.2014,872.344,16.9139
Kurtosis,2606.77,336.858,204658,204657,443.158,1.03986e+06,1.03933e+06,1.03933e+06,1.03717e+06,336.364,336.364,845899,312.428
Variance,1.11228e+19,2.07406e+07,103551,103551,0.192233,2.02345e+08,2.02396e+08,2.02396e+08,2.02607e+08,2.07775e+07,2.07775e+07,2.24337e+08,1.96532e+07
StdDeviation,3.33508e+09,4554.19,321.793,321.794,0.438444,14224.8,14226.6,14226.6,14234,4558.24,4558.24,14977.9,4433.2